name: Tilemaker

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Download Tilemaker
        run: |
          wget https://github.com/systemed/tilemaker/releases/download/v2.2.0/tilemaker-ubuntu-18.04.zip
          unzip -j tilemaker-ubuntu-18.04.zip
          chmod +x ./tilemaker

      - name: Download coastline
        run: |
          wget https://osmdata.openstreetmap.de/download/water-polygons-split-4326.zip
          unzip -j -d coastline water-polygons-split-4326.zip

      - name: Download data file
        run: aria2c -x 16 -s 16 -k 1M https://download.geofabrik.de/north-america/us/california-latest.osm.pbf

      - name: Run Tilemaker
        run: |
          ./tilemaker \
            --input california-latest.osm.pbf \
            --output california-latest.mbtiles \
            --config config-openmaptiles.json \
            --process process-openmaptiles.lua

      - name: Upload the .mbtiles file
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: california-latest.mbtiles
